// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ajafcwrzwibyibkewzgj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFqYWZjd3J6d2lieWlia2V3emdqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzgyNzUxNTcsImV4cCI6MjA1Mzg1MTE1N30.SI9DU4HLxPQ6yxyCoz7TtZSuWQDyacgrZoiYn6MlGSs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);